spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.104.223.125:3307/yida_dev?useUnicode=true&characterEncoding=utf-8&useSSL=false
#    url: jdbc:mysql://39.108.158.31:3306/yida?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&useSSL=false&rewriteBatchedStatements=TRUE
    username: root
    password: iswater
logging:
 config: classpath:logback-dev.xml

img:
#文件保存路径
 uploadPath:  /var/yida/
 #返回给前端的访问路径
 visitPath: /static/imgs/
 #重命名图片前缀
 prefix: etar-
 #环境地址
 imgUrl: http://iotsvr.he-live.com

mqtt:
  host: tcp://iotsvr.he-live.com:3883
  clientid: backend:${random.int[1024,65536]}
  username: admin
  password: admin
  topic: topic
  timeout: 3000
  keepalive: 2000

#EMQ Basic 认证
appid: 38fdb2362e4f #21c40690fa4e5
appsecret: Mjg4MzA3ODA2ODYzNzQzMjQ1MDUxNjQ3MTIzNTM1OTUzOTC #Mjg1NjE0MzE1MTM3NTY0Mzc1MjI3MTg2NDA1MTc1NDU5ODE
#EMQ服务器地址
emq_server: http://iotsvr.he-live.com:9080
#接口地址
connect_url: /api/v3/connections/
route_url: /api/v3/routes/

server:
  port: 7001



