spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://123.57.148.29:3306/yida-dev?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&useSSL=true&rewriteBatchedStatements=TRUE
#    url: jdbc:mysql://39.108.158.31:3306/yida?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&useSSL=true&rewriteBatchedStatements=TRUE
    username: root
    password: iswater
  jpa:
    show-sql: true
logging:
 config: classpath:logback-dev.xml

img:
#文件保存路径
 uploadPath:  /var/yida/
 #返回给前端的访问路径
 visitPath: /static/imgs/
 #重命名图片前缀
 prefix: etar-
 #环境地址
 imgUrl: http://iotsvr.he-live.com

mqtt:
  host: tcp://39.105.103.1:1883
  clientid: backend1
  username: admin
  password: password
  topic: topic
  timeout: 3000
  keepalive: 2000

#EMQ Basic 认证
appid: 21c40690fa4e5
appsecret: Mjg1NjE0MzE1MTM3NTY0Mzc1MjI3MTg2NDA1MTc1NDU5ODE
#EMQ服务器地址
emq_server: http://39.105.103.1:8080
#接口地址
connect_url: /api/v3/connections/

http:
  port: 8787



