version: '3'
services:
  eureka-server:
      image: eureka-server:0.0.1
      container_name: yida-eureka-server
      build:
        context: eureka
        dockerfile: Dockerfile
      restart: always
      networks:
        - yida
      ports:
        - 8761:8761
      volumes:
        - /etc/timezone:/etc/timezone
        - /etc/localtime:/etc/localtime
      env_file: .env
  zull-service:
      image: zull-service:0.0.1
      container_name: yida-zull-service
      build:
        context: zuul
        dockerfile: Dockerfile
      restart: always
      networks:
        - yida
      ports:
        - 8769:8769
      volumes:
        - /etc/timezone:/etc/timezone
        - /etc/localtime:/etc/localtime
      env_file: .env
      depends_on:
        - eureka-server

  auth-service:
    image: auth-service:0.0.1
    container_name: yida-auth-service
    build:
      context: auth
      dockerfile: Dockerfile
    networks:
      - yida
    ports:
      - 9002:9002
    volumes:
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
    depends_on:
      - eureka-server
      - zull-service

  mng-service:
    image: mng-service:0.0.1
    container_name: yida-mng-service
    build:
      context: mng
      dockerfile: Dockerfile
    networks:
      - yida
    ports:
      - 8787:8787
    deploy:
      resources:
        limits:
          memory: 100M
        reservations:
          memory: 80M
    volumes:
     - /etc/timezone:/etc/timezone
     - /etc/localtime:/etc/localtime
    depends_on:
      - eureka-server
      - zull-service
      - mysql

  mqtt-service:
    image: mqtt-service:0.0.1
    container_name: yida-mqtt-service
    build:
      context: mqtt
      dockerfile: Dockerfile
    networks:
      - yida
    ports:
      - 7001:7001
    volumes:
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
    depends_on:
      - eureka-server
      - zull-service
      - auth-service
      - mysql
  miniprogram-service:
    image: miniprogram-service:0.0.1
    container_name: yida-miniprogram-service
    build:
      context: mini
      dockerfile: Dockerfile
    networks:
      - yida
    ports:
      - 443:443
    volumes:
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
    depends_on:
      - eureka-server
      - zull-service
      - mysql
  nginx:
    image: docker.io/nginx:latest
    container_name: yida-nginx-service
    volumes:
      - ./nginx/www:/web
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/logs:/log
      - /var/yida:/var/yida
    command: nginx -g "daemon off;"
    networks:
      - yida
    ports:
      - 8092:81

  mysql:
    image: docker.io/mysql:5.7
    container_name: yida-mysql
    restart: always
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
      --max_allowed_packet=128M;
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: iswater
      TZ: Asia/Shanghai
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/conf:/etc/mysql/conf.d
      - ./mysql/logs:/logs
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
    networks:
      - yida
networks:
  yida:
    driver: bridge
