server:
   tomcat:
      max-threads: 1000
      uri-encoding: UTF-8
      max-http-header-size: 10240
      max-http-post-size: 10240
      max-connections: 20000
spring:
    profiles:
        active: @profileActive@
    application:
        name: auth-service
    http:
      encoding:
        force: true
        charset: utf-8
        enabled: true

eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://admin:xiaoheDev520@${eureka.instance.hostname}:8761/eureka/
feign:
  hystrix:
    enabled: true
#请求处理的超时时间
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
mqtt:
  username: admin
  password: admin
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 6000






