spring:
 jpa:
  show-sql: true

# shardingJdbc配置
sharding:
 jdbc:
  data-sources:
   ds_master:
    driver-class-name: com.mysql.jdbc.Driver
    jdbcUrl: jdbc:mysql://47.104.223.125:3307/yida_dev?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: iswater
   ds_slave_0:
    driver-class-name: com.mysql.jdbc.Driver
    jdbcUrl: jdbc:mysql://47.104.223.125:3307/yida_dev?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: iswater
  master-slave-rule:
   name: ds_ms
   master-data-source-name: ds_master
   slave-data-source-names: [ds_master]  #多个用逗号隔开
   load-balance-algorithm-type: round_robin
   props:
    sql.show: true
logging:
 config: classpath:logback-dev.xml

img:
 #文件保存路径
 uploadPath:  /var/yida/
 #返回给前端的访问路径
 visitPath: /static/imgs/
 #重命名图片前缀
 prefix: etar-
 #环境地址
 imgUrl: http://iotsvr.he-live.com

firmware:
 #文件保存路径
 uploadPath:  /var/firmware/
 #返回给前端的访问路径
 visitPath: /firmware/
 #重命名图片前缀
 prefix: firmware-
 #环境地址
 firmwareUrl: http://iotsvr.he-live.com


server:
 port: 8787



