# shardingJdbc配置
sharding:
  jdbc:
    data-sources:
      ds_master:
        driver-class-name: com.mysql.jdbc.Driver
        jdbcUrl: jdbc:mysql://123.57.148.29:3306/yida1?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&useSSL=false&rewriteBatchedStatements=TRUE
        username: root
        password: iswater
      ds_slave_0:
        driver-class-name: com.mysql.jdbc.Driver
        jdbcUrl: jdbc:mysql://123.57.148.29:3306/yida1?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&useSSL=false&rewriteBatchedStatements=TRUE
        username: root
        password: iswater
    master-slave-rule:
      name: ds_ms
      master-data-source-name: ds_master
      slave-data-source-names: [ds_master]  #多个用逗号隔开
      load-balance-algorithm-type: round_robin
      props:
        sql.show: true
logging:
  config: classpath:logback-prod.xml

img:
  #文件保存路径
  uploadPath: /var/yida/
  #返回给前端的访问路径
  visitPath: /static/imgs/
  #重命名图片前缀
  prefix: etar-
  #环境地址
  imgUrl: http://123.57.148.29

firmware:
 #文件保存路径
 uploadPath:  /var/firmware/
 #返回给前端的访问路径
 visitPath: /firmware/
 #重命名图片前缀
 prefix: firmware-
 #环境地址
 firmwareUrl: http://123.57.148.29

mqtt:
  host: tcp://yidasvr.zsxiaohe.com:1883
  clientid: backend:${random.int[1024,65536]}
  username: admin
  password: admin
  topic: topic1
  timeout: 3000
  keepalive: 2000

#EMQ Basic 认证
appid: 01d6f2d460b8a
appsecret: Mjg1NjE1MzYzNzI4MjUyMDI2ODg4MzAwOTE0MTI4MzIyNTG
#服务器地址
emq_server: http://yidasvr.zsxiaohe.com:18080
#接口地址
connect_url: /api/v3/connections/
route_url: /api/v3/routes/

server:
  port: 8787

