spring:
  jpa:
    show-sql: true

# shardingJdbc配置
sharding:
  jdbc:
    data-sources:
      ds_master:
        driver-class-name: com.mysql.jdbc.Driver
        jdbcUrl: jdbc:mysql://123.57.148.29:3306/yida-dev?useUnicode=true&characterEncoding=utf-8&useSSL=true
        username: root
        password: iswater
      ds_slave_0:
        driver-class-name: com.mysql.jdbc.Driver
        jdbcUrl: jdbc:mysql://39.108.158.31:3306/ds_0?useUnicode=true&characterEncoding=utf-8&useSSL=true
        username: root
        password: admin
    master-slave-rule:
      name: ds_ms
      master-data-source-name: ds_master
      slave-data-source-names: [ds_master]  #多个用逗号隔开
      load-balance-algorithm-type: round_robin
      props:
        sql.show: true
logging:
  config: classpath:logback-local.xml

img:
  #文件保存路径
  uploadPath: D:/img/
  #返回给前端的访问路径
  visitPath: /static/imgs/
  #重命名图片前缀
  prefix: etar-
  #环境地址
  imgUrl: http://localhost

mqtt:
  host: tcp://39.105.103.1:1883
  clientid: backend:${random.int[1024,65536]}
  username: admin
  password: password
  topic: topic
  timeout: 3000
  keepalive: 2000

#EMQ Basic 认证
appid: 21c40690fa4e5
appsecret: Mjg1NjE0MzE1MTM3NTY0Mzc1MjI3MTg2NDA1MTc1NDU5ODE
#EMQ服务器地址
emq_server: http://39.105.103.1:8080
#接口地址
connect_url: /api/v3/connections/

server:
  port: 8787
