
server:
  port: 17001  #测试环境8769
  tomcat:
      max-threads: 1000
      uri-encoding: UTF-8
      max-http-header-size: 10240
      max-http-post-size: 10240
      max-connections: 20000
spring:
  application:
    name: zuul-service
eureka:
  instance.prefer-ip-address: false
  client.serviceUrl.defaultZone: http://admin:xiaoheDev520@${eureka.instance.hostname}:8761/eureka/
  instance:
    hostname: localhost
#路由规则
zuul:
  routes:
    mng-service:
      serviceId: mng-service
      path: /mng/**
    devcontrol:
      serviceId: mqtt-service
      path: /devcontrol/**
    auth:
      serviceId: auth-service
      path: /auth/**
#    mini-service:
#      url: https://iotsvr.zsxiaohe.com:443
#      path: /mini/**
ribbon:
  # 连接超时时间(ms)
  ConnectTimeout: 1050
  # 通信超时时间(ms)
  ReadTimeout: 6000
  # 是否对所有操作重试
  OkToRetryOnAllOperations: true
  # 同一服务不同实例的重试次数
  MaxAutoRetriesNextServer: 2
  # 同一实例的重试次数
  MaxAutoRetries: 1

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 6000
